<a href="https://colab.research.google.com/github/chenpetro/04_08_22_Lesson8_Semester2_Web_1_01_2/blob/main/2026_03_20_cleaning_data_Petro_Chen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv("batch1.dat", sep=" ")

In [ ]:
df

,gas,1,2,3,4,5,6,7,8,9,...,119,120,121,122,123,124,125,126,127,128
0,None,15596.1621,1.868245,2.371604,2.803678,7.512213,-2.739388,-3.344671,-4.847512,15326.6914,...,-1.071137,-3.037772,3037.0390,3.972203,0.527291,0.728443,1.445783,-0.545079,-0.902241,-2.654529
1,None,26402.0704,2.532401,5.411209,6.509906,7.658469,-4.722217,-5.817651,-7.518333,23855.7812,...,-1.530519,-1.994993,4176.4453,4.281373,0.980205,1.628050,1.951172,-0.889333,-1.323505,-1.749225
2,None,42103.5820,3.454189,8.198175,10.508439,11.611003,-7.668313,-9.478675,-12.230939,37562.3008,...,-2.384784,-2.867291,5914.6685,5.396827,1.403973,2.476956,3.039841,-1.334558,-1.993659,-2.348370
3,None,42825.9883,3.451192,12.113940,16.266853,39.910056,-7.849409,-9.689894,-11.921704,38379.0664,...,-2.607199,-3.058086,6147.4744,5.501071,1.981933,3.569823,4.049197,-1.432205,-2.146158,-2.488957
4,None,58151.1757,4.194839,11.455096,15.715298,17.654915,-11.083364,-13.580692,-16.407848,51975.5899,...,-3.594763,-4.181920,8158.6449,7.174334,1.993808,3.829303,4.402448,-1.930107,-2.931265,-4.088756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,None,74805.0518,6.707129,15.446750,19.415134,20.782742,-12.073277,-15.890503,-33.655074,71893.4726,...,-0.727597,-1.928152,3208.7706,3.548801,0.692627,0.992265,1.274428,-0.481713,-0.705449,-2.153036
441,None,92035.5156,7.775487,21.173590,27.620422,29.159638,-14.717438,-17.631495,-21.352693,88619.7480,...,-1.015120,-2.734727,4009.7310,4.051835,0.983568,1.454702,1.736482,-0.648578,-1.101465,-3.118286
442,None,107898.2334,8.994761,25.131079,33.771374,37.121172,-17.064423,-23.058288,-66.829676,103904.5332,...,-1.279203,-1.539648,4834.6333,4.605179,1.218879,1.846645,2.245026,-0.831980,-1.299345,-3.860362
443,None,119795.0352,9.582606,28.944716,39.290350,41.062943,-18.824844,-22.903238,-29.631211,115551.0313,...,-1.556993,-3.688803,5555.9392,5.015334,1.413263,2.199541,3.252978,-0.970762,-1.693868,-2.720472
444,None,140782.2978,10.975342,35.524802,59.584134,50.208230,-21.607891,-25.081263,-72.701125,135883.9053,...,-2.269665,-6.156940,6816.6381,5.913717,1.787649,3.051548,3.255161,-1.281157,-2.332680,-3.735087

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 444 entries, 0 to 443
Columns: 129 entries, 1 to 128:-2.654529
dtypes: int64(1), object(128)
memory usage: 447.6+ KB

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [gas, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]
Index: []

[0 rows x 129 columns]

In [ ]:
df.iloc[0]

gas          None
1      15596.1621
2        1.868245
3        2.371604
4        2.803678
          ...
124      0.728443
125      1.445783
126     -0.545079
127     -0.902241
128     -2.654529
Name: 0, Length: 129, dtype: object

In [ ]:
df.iloc[0:0]

Empty DataFrame
Columns: [gas, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]
Index: []

[0 rows x 129 columns]

In [ ]:
with open("batch1.dat", "r") as f:
    print("First 5 lines:")
    for i, line in enumerate(f):
        if i >= 5:
            break
        print(repr(line.strip()))

First 5 lines:
'1 1:15596.162100 2:1.868245 3:2.371604 4:2.803678 5:7.512213 6:-2.739388 7:-3.344671 8:-4.847512 9:15326.691400 10:1.768526 11:2.269085 12:2.713374 13:6.915721 14:-2.488324 15:-3.082212 16:-5.056975 17:2789.383100 18:2.754759 19:0.430440 20:0.649457 21:1.795029 22:-0.426662 23:-0.584313 24:-1.438976 25:2581.568600 26:2.680623 27:0.399746 28:0.605065 29:1.786704 30:-0.400115 31:-0.550743 32:-1.728611 33:685.399400 34:1.682904 35:0.122736 36:0.223703 37:0.584691 38:-0.138196 39:-0.236907 40:-0.781959 41:797.773800 42:1.742488 43:0.152483 44:0.218904 45:0.841862 46:-0.164646 47:-0.315720 48:-0.791447 49:3128.848900 50:3.605537 51:0.532422 52:0.763062 53:2.118983 54:-0.557197 55:-0.809953 56:-2.344130 57:3136.877800 58:3.555169 59:0.535883 60:0.761388 61:1.499244 62:-0.571480 63:-0.944425 64:-2.658358 65:13540.673800 66:1.765738 67:2.006883 68:2.519022 69:6.261430 70:-2.172101 71:-2.694967 72:-3.791499 73:13831.753900 74:1.746493 75:2.057165 76:2.391239 77:5.695234 78:-2.350776 79:-2.888766 80:-8.129869 81:3020.919100 82:2.819354 83:0.474520 84:0.723993 85:2.160130 86:-0.467900 87:-0.638167 88:-1.643650 89:2185.974100 90:2.949381 91:0.342575 92:0.515090 93:1.340477 94:-0.361030 95:-0.493482 96:-1.200617 97:862.747900 98:1.779291 99:0.165138 100:0.246473 101:1.358106 102:-0.187465 103:-0.416382 104:-1.058061 105:1059.756200 106:1.896047 107:0.198946 108:0.334017 109:0.815048 110:-0.204467 111:-0.345119 112:-0.969336 113:3357.112400 114:3.860647 115:0.580818 116:0.806830 117:1.729739 118:-0.619214 119:-1.071137 120:-3.037772 121:3037.039000 122:3.972203 123:0.527291 124:0.728443 125:1.445783 126:-0.545079 127:-0.902241 128:-2.654529'
'1 1:26402.070400 2:2.532401 3:5.411209 4:6.509906 5:7.658469 6:-4.722217 7:-5.817651 8:-7.518333 9:23855.781200 10:2.164706 11:4.901063 12:5.971392 13:6.978131 14:-4.199424 15:-5.221090 16:-7.604863 17:3882.905700 18:3.155054 19:0.802987 20:1.172245 21:1.570895 22:-0.697881 23:-0.944655 24:-1.334743 25:3651.042700 26:3.130669 27:0.739278 28:1.101765 29:1.428631 30:-0.659641 31:-0.915543 32:-1.334217 33:982.949000 34:1.933877 35:0.233308 36:0.378052 37:0.717916 38:-0.225572 39:-0.354591 40:-0.748061 41:1162.237800 42:2.039431 43:0.278337 44:0.486908 45:0.840494 46:-0.271369 47:-0.473164 48:-0.718214 49:4332.154300 50:3.990162 51:1.002503 52:1.586233 53:1.926608 54:-0.913245 55:-1.335612 56:-1.773328 57:4387.528400 58:4.011519 59:1.009769 60:1.647830 61:1.962858 62:-0.944028 63:-1.631468 64:-1.925095 65:20553.564500 66:2.108870 67:4.266941 68:5.185937 69:6.398693 70:-3.636176 71:-4.497039 72:-7.464548 73:22540.193300 74:2.222146 75:4.621283 76:5.573620 77:6.756039 78:-3.986434 79:-4.953663 80:-6.561748 81:4240.301100 82:3.262893 83:0.887237 84:1.297617 85:1.630074 86:-0.768036 87:-1.244472 88:-1.419646 89:3079.062100 90:3.399659 91:0.649639 92:0.948781 93:1.369550 94:-0.598444 95:-0.820868 96:-1.081919 97:1237.013100 98:2.067927 99:0.305793 100:0.558008 101:0.948564 102:-0.289557 103:-0.501078 104:-1.191404 105:1459.635600 106:2.149242 107:0.361007 108:0.614619 109:0.950204 110:-0.327339 111:-0.503861 112:-0.838039 113:4685.775300 114:4.277604 115:1.080629 116:1.818559 117:2.237534 118:-1.004812 119:-1.530519 120:-1.994993 121:4176.445300 122:4.281373 123:0.980205 124:1.628050 125:1.951172 126:-0.889333 127:-1.323505 128:-1.749225'
'1 1:42103.582000 2:3.454189 3:8.198175 4:10.508439 5:11.611003 6:-7.668313 7:-9.478675 8:-12.230939 9:37562.300800 10:2.840403 11:7.386357 12:9.511703 13:12.129657 14:-6.689464 15:-8.184333 16:-10.196169 17:5476.389800 18:3.929721 19:1.132118 20:1.717418 21:2.050157 22:-1.052941 23:-1.436270 24:-1.956262 25:5140.830200 26:3.880357 27:1.054304 28:1.649600 29:1.964727 30:-0.995282 31:-1.377502 32:-1.844021 33:1409.218300 34:2.316449 35:0.335154 36:0.572576 37:0.932730 38:-0.337312 39:-0.532147 40:-1.011991 41:1647.678000 42:2.443898 43:0.405582 44:0.725644 45:1.006433 46:-0.403554 47:-0.676717 48:-1.008518 49:6145.665900 50:4.998625 51:1.426344 52:2.407405 53:2.856787 54:-1.377070 55:-1.994748 56:-2.445191 57:6197.304700 58:4.997810 59:1.473118 60:2.545978 61:3.331699 62:-1.420663 63:-2.185120 64:-2.625092 65:32366.933600 66:2.742087 67:6.419288 68:8.290210 69:9.709606 70:-5.792984 71:-7.171543 72:-9.797253 73:35597.002000 74:2.916899 75:6.969954 76:8.951225 77:10.413684 78:-6.441517 79:-7.914062 80:-9.973361 81:5968.866600 82:4.056138 83:1.262938 84:1.935885 85:2.346947 86:-1.159097 87:-1.791556 88:-2.233596 89:4409.172100 90:4.286887 91:0.917809 92:1.390353 93:1.810937 94:-0.909467 95:-1.254904 96:-1.732933 97:1735.038300 98:2.466508 99:0.450574 100:0.841068 101:1.808291 102:-0.426742 103:-0.711579 104:-1.129027 105:2040.152800 106:2.572696 107:0.509803 108:0.932630 109:1.248513 110:-0.475471 111:-0.730332 112:-1.126488 113:6630.183600 114:5.369827 115:1.567405 116:2.790448 117:3.279244 118:-1.518135 119:-2.384784 120:-2.867291 121:5914.668500 122:5.396827 123:1.403973 124:2.476956 125:3.039841 126:-1.334558 127:-1.993659 128:-2.348370'
'1 1:42825.988300 2:3.451192 3:12.113940 4:16.266853 5:39.910056 6:-7.849409 7:-9.689894 8:-11.921704 9:38379.066400 10:2.851173 11:10.840889 12:14.566782 13:39.100492 14:-6.878915 15:-8.470092 16:-10.739835 17:5670.714400 18:3.994661 19:1.587322 20:2.963585 21:2.889819 22:-1.116192 23:-1.504534 24:-2.159710 25:5343.833700 26:3.962529 27:1.479765 28:2.653653 29:2.753598 30:-1.061584 31:-1.465905 32:-2.027846 33:1499.398700 34:2.415714 35:0.476230 36:0.834066 37:1.316245 38:-0.373295 39:-0.562486 40:-1.005683 41:1747.036700 42:2.543528 43:0.575862 44:1.045360 45:1.582893 46:-0.437584 47:-0.720969 48:-1.172276 49:6361.217900 50:5.118540 51:2.016031 52:3.511800 53:3.989634 54:-1.468832 55:-2.164832 56:-2.952224 57:6443.575800 58:5.138118 59:2.067199 60:3.618647 61:4.262233 62:-1.521618 63:-2.328864 64:-2.871851 65:33300.605500 66:2.765042 67:9.397436 68:13.022406 69:29.111833 70:-5.999020 71:-7.466897 72:-9.590399 73:36487.121100 74:2.937415 75:10.300845 76:14.504802 77:29.353683 78:-6.624663 79:-8.135443 80:-10.433171 81:6187.144600 82:4.127966 83:1.772427 84:3.242992 85:3.232927 86:-1.233289 87:-1.676956 88:-2.110830 89:4570.344300 90:4.382205 91:1.298156 92:2.334433 93:2.427754 94:-0.964750 95:-1.315083 96:-1.575122 97:1837.055100 98:2.560248 99:0.626115 100:1.226975 101:1.828968 102:-0.463871 103:-0.785627 104:-1.249903 105:2144.843600 106:2.660842 107:0.714324 108:1.322181 109:1.883925 110:-0.513716 111:-0.777995 112:-1.134804 113:6933.284400 114:5.507270 115:2.215701 116:4.042550 117:4.675110 118:-1.644751 119:-2.607199 120:-3.058086 121:6147.474400 122:5.501071 123:1.981933 124:3.569823 125:4.049197 126:-1.432205 127:-2.146158 128:-2.488957'
'1 1:58151.175700 2:4.194839 3:11.455096 4:15.715298 5:17.654915 6:-11.083364 7:-13.580692 8:-16.407848 9:51975.589900 10:3.480866 11:10.409176 12:14.379885 13:15.387529 14:-9.543570 15:-11.707853 16:-14.370753 17:7483.365600 18:5.074172 19:1.576100 20:2.558010 21:3.389052 22:-1.515863 23:-2.059119 24:-2.494956 25:6995.239600 26:4.995555 27:1.474554 28:2.500523 29:2.981684 30:-1.436586 31:-2.006992 32:-2.424730 33:1976.101100 34:2.893531 35:0.480052 36:0.871868 37:1.301642 38:-0.487181 39:-0.753798 40:-1.628245 41:2286.879200 42:3.058936 43:0.581186 44:1.145093 45:1.508896 46:-0.582666 47:-0.949063 48:-1.270385 49:8474.369600 50:6.673105 51:2.025916 52:3.650673 53:4.291259 54:-1.985612 55:-2.992950 56:-3.446640 57:8547.214600 58:6.689090 59:2.078846 60:3.889228 61:4.392452 62:-2.073675 63:-3.305190 64:-3.792976 65:45212.652300 66:3.384210 67:9.083462 68:12.575800 69:13.600584 70:-8.326705 71:-10.152834 72:-12.301180 73:49670.978500 74:3.602189 75:9.905257 76:13.542131 77:14.934498 78:-9.292178 79:-12.009161 80:-13.677505 81:8128.656100 82:5.244599 83:1.762437 84:2.896088 85:3.339938 86:-1.674587 87:-2.412309 88:-2.787965 89:6086.254500 90:5.642596 91:1.293397 92:2.071232 93:2.683706 94:-1.316635 95:-1.798607 96:-3.026084 97:2388.189100 98:3.067174 99:0.632552 100:1.322201 101:1.666461 102:-0.611909 103:-1.018826 104:-1.770461 105:2784.495200 106:3.196657 107:0.716810 108:1.419936 109:1.845668 110:-0.663462 111:-1.022919 112:-1.602759 113:9179.233800 114:7.214645 115:2.236090 116:4.367815 117:4.946454 118:-2.249702 119:-3.594763 120:-4.181920 121:8158.644900 122:7.174334 123:1.993808 124:3.829303 125:4.402448 126:-1.930107 127:-2.931265 128:-4.088756'

In [ ]:
def parse_batch1_dat(path):
    rows = []
    gas_id = None

    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            # Gas‑label line: single digit 1–6
            if len(line) == 1 and line in "123456":
                gas_id = int(line)
                continue

            # Otherwise this line is a feature row: 1:... 2:...
            features = {"gas": gas_id}  # attach gas label from previous line
            for part in line.split():
                if ":" not in part:
                    continue  # ignore malformed parts
                idx, val = part.split(":", 1)
                features[int(idx)] = float(val)

            rows.append(features)

    return pd.DataFrame(rows)

df = parse_batch1_dat("batch1.dat")
print(df.shape)
print(df.head())

(445, 129)
    gas           1         2          3          4          5          6  \
0  None  15596.1621  1.868245   2.371604   2.803678   7.512213  -2.739388
1  None  26402.0704  2.532401   5.411209   6.509906   7.658469  -4.722217
2  None  42103.5820  3.454189   8.198175  10.508439  11.611003  -7.668313
3  None  42825.9883  3.451192  12.113940  16.266853  39.910056  -7.849409
4  None  58151.1757  4.194839  11.455096  15.715298  17.654915 -11.083364

           7          8           9  ...       119       120        121  \
0  -3.344671  -4.847512  15326.6914  ... -1.071137 -3.037772  3037.0390
1  -5.817651  -7.518333  23855.7812  ... -1.530519 -1.994993  4176.4453
2  -9.478675 -12.230939  37562.3008  ... -2.384784 -2.867291  5914.6685
3  -9.689894 -11.921704  38379.0664  ... -2.607199 -3.058086  6147.4744
4 -13.580692 -16.407848  51975.5899  ... -3.594763 -4.181920  8158.6449

        122       123       124       125       126       127       128
0  3.972203  0.527291  0.728443  1.445783 -0.545079 -0.902241 -2.654529
1  4.281373  0.980205  1.628050  1.951172 -0.889333 -1.323505 -1.749225
2  5.396827  1.403973  2.476956  3.039841 -1.334558 -1.993659 -2.348370
3  5.501071  1.981933  3.569823  4.049197 -1.432205 -2.146158 -2.488957
4  7.174334  1.993808  3.829303  4.402448 -1.930107 -2.931265 -4.088756

[5 rows x 129 columns]